channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.6
  - pip
  - gputools
  - h5py=2.10.0
  - keras=2.3.1
  - numpy=1.19.1
  - scikit-image=0.17.2
  - tensorflow=1.15
  - tensorflow-gpu=1.15
  - z5py=2.0.5
  - pip:
    - edt
    - gputools
    - git+https://github.com/mpicbg-csbd/stardist@refinement
